### ISSUE TITLE
Broken build for `PIP_COMPILE_ARGS="-P pyarrow==0.12.1 -P dask<2.2.0"`

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#150]

**Comment by crepererum** [comment]
Probably because pip-compile is not a proper SAT solver. The issue is that it resolves `distributed==2.5.2` now which then requires `dask>=2.3`. Since pip-compile doesn't do any backtracking, it just fails in that case. Constraining distributed as well would help, but it is kinda hack since this was never the original intention.

**Comment by lr4d** [comment]
yeah I realized that constraining distributed works. I don't see a better solution atm, since we can't use conda because of dependencies not being uploaded there

**Comment by fjetter** [comment]
Moving on to Conda for the travis builds would help here, too
