### ISSUE TITLE
drop pyarrow 0.12.x support

### ISSUE THREAD

**Issue by crepererum** [JDASoftwareGroup/kartothek#161]
After #155, I think we can safely drop 0.12.x support (will still support 0.13.x, 0.14.1 and 0.15.x which are 3 major releases).

**Comment by crepererum** [comment]
This should only drop library support, not the read support (see `test_arrow_compat.py`).

**Comment by fjetter** [comment]
> This should only drop library support, not the read support

Just to clarify: We would keep the backwards compatibility read test to ensure that we can still read old datasets but drop arrow 0.12.X testing and would remove the respective workarounds in ktk, s.t. the library will no longer be usable with arrow 0.12.X?

If so, yes we should drop 0.12.X

@xhochy do you have a gut feeling about how long people take to move on to new arrow versions ? I'm wondering if the support of three major versions (13, 14, 15) is not even too much and we should drop 13 as well soon-ish

**Comment by xhochy** [comment]
People move fairly quickly except for two users:

* Using Spark: They generally move very slow, not because Spark is not updated but because they don't update their Spark.
* Anaconda defaults channel is slow with updating Arrow: They are nowadays at 0.13, so we're fine with dropping 0.12 here.

Otherwise people move fast, we should stick to the current and the previous minor (0.14.x, 0.15.x) release.
