### ISSUE TITLE
Option to pass Arrow Schema when creating a dataset

### ISSUE THREAD

**Issue by ged-steponavicius** [JDASoftwareGroup/kartothek#228]
Is there a way to pass schema to store_dataframes_as_dataset? I can see make_meta checks if obj passed to is pa.Schema type and returns it, However, the input is missing from store_dataframes_as_dataset. An alternative approach could be passing Arrow table instead of df.

For examples when converting df to Arrow table we have from_pandas which accepts table schema:
pa.Table.from_pandas(df,schema = table_schema)

I would like to define a schema instead of kartothek 'guessing' field types. The underlying issue I have encountered is with partitioned datasets where only some partitions have additional columns - kartothek guess data type to be null when only a single partition is written, despite field types being set to correct pandas dtype.

**Comment by lr4d** [comment]
Atm this is not supported in a straightforward way (at least AFAIK). I am curious about the issue you encountered though, could you provide a minimal example for that and open a new issue for this?

**Comment by fjetter** [comment]
> could be passing Arrow table instead of df

This is something we would like to look into in the future but we still rely on a few pandas.DataFrame operations, e.g. groupby. Once this is available for arrow tables we can look into accepting / returning arrow tables directly. This might take a while, though.

> The underlying issue I have encountered is with partitioned datasets where only some partitions have additional columns 

Well, that's actually something we deliberately want to forbid at the moment. One of the core concepts of kartothek is to ensure a consistent table and a consistent schema definition is part of this.
If this guarantee is not given we run into very weird issues when querying data since partitions / data frames with different schema would need to be somehow merged and it is not clear how this would look like, especially with the limitations of pandas only allowing nulls for a few data types (at least pre 1.0).

According to the documentation of [`pyarrow.Table`](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_pandas) the schema keyword would also not suit your need if I understand this correctly since it will raise if a specified column doesn't exist.

> kartothek guess data type to be null when only a single partition is written, despite field types being set to correct pandas dtype.

Indeed, in the case of an initial dataset creation where we only store an empty partition this might happen and certain functionality may be broken.


Can you provide a few more details about what you are trying to achieve? In our experience, so far, the automatic inference of the schema is a great feature in terms of usability but I'll gladly change my opinion there :)

Full disclosure:
We currently offer a method which will creates what we refer to as a dataset header, i.e. it will create the dataset metadata and the schema. There, we actually accept the schema itself. There have been a lot discussions (internally) about removing this, though, since it is rather low-level and felt unnecessary. Still, if you're trying to commit a partition to this header which lacks all defined fields it will raise.

**Comment by ged-steponavicius** [comment]
The example I mentioned in my original comment, it actually appears to work OK now without the need to pass in schema:

`import pandas as pd
from functools import partial
from tempfile import TemporaryDirectory
from storefact import get_store_from_url
from kartothek.io.eager import store_dataframes_as_dataset,update_dataset_from_dataframes

dataset_dir = TemporaryDirectory()

store_factory = partial(get_store_from_url, f"hfs://{dataset_dir.name}")
store = get_store_from_url( f"hfs://{dataset_dir.name}")

df = pd.DataFrame([{'part':1,'id':1,'col1':'abc'},
                   {'part':2,'id':2,'col1':np.nan}])

dm = store_dataframes_as_dataset(
    store_factory,
    "sample_ds", 
    [df],
    overwrite=True,
    partition_on=['part']

 )

dm = update_dataset_from_dataframes(
    [df.loc[df['part']==2]],
    store_factory,
    "sample_ds",
    partition_on=['part'],
    delete_scope=[{'part':2}]

 )
`

However, creating an empty DS and then writing a single partition throws schema violation:
`
schema = pa.Schema.from_pandas(df)

meta = create_empty_dataset_header(store = store,
                            dataset_uuid='sample_ds',
                            table_meta={'table':schema},
                            partition_on=['part'],
                            overwrite=True)

new_partitions = [
                write_single_partition(
                    store=store,
                    dataset_uuid='sample_ds',
                    data=[{'table':df.loc[df['part']==1]}],
                    metadata=meta,
                    partition_on=['part'],
                )
            ]
`
Error message: 
ValueError: Schema violation

Origin schema: {sample_ds/table/_common_metadata}
Origin reference: {table/part=1/1c68a6b638584d60b38a931adf54cdb0}

Diff:
Arrow schema:
@@ -1,3 +1,3 @@

 part: int64
+id: int64
 col1: string
-id: int64


pandas 1.0.1
pyarrow 0.16
kartothek 3.7.0

**Comment by fjetter** [comment]
The last exception you encountered, is indeed a bug. See #245 for the fix

**Comment by fjetter** [comment]
FYI: If you intend to use `create_empty_dataset_header` because you want to provide the pyarrow schema yourself, you can still use the ordinary update pipelines and I highly recommend to use those instead of `write_single_partition + commit` if possible.
