### ISSUE TITLE
Are concurrent writes with update_dataset_from_ddf possible?

### ISSUE THREAD

**Issue by brl0** [JDASoftwareGroup/kartothek#281]
Is it safe to update separate partitions in a Kartothek dataset from multiple processes simultaneously with update_dataset_from_ddf?

**Comment by xhochy** [comment]
No, it is not safe as all functions that write data will rewrite the single metadata json at the end. Thus if you write two partitions in parallel, only one will end up in the dataset.

Kartothek is built with the tradeoff to support parallel reads (even during writes) to a store that doesn't support any file locks but at the cost that only process cam write at a time.

**Comment by fjetter** [comment]
It is true what @xhochy wrote but I'd like to give a bit more context.

First of all, just to repeat, kartothek **does not offer serializable isolation** (as in I of ACID, not the best source since this is not a DBMS but [wiki](https://en.wikipedia.org/wiki/Isolation_(database_systems)) gives a brief overview)

Every writing `kartothek` pipeline has a commit at the very end of the pipeline (in practice this commit will update a single file `<UUID>.by-metadata.json` which is the source of truth for all datasets). Everything leading up to this commit can be done in parallel since all files are usually unique, either by using timestamps or proper UUIDs. Only the very final step, the commit, must not happen simultaneously. If there are two competing commits, one of them will win and the other will be ignored. We currently do not have a mechanism to detect which commit was successful or not and can therefore not try to reapply the unsuccessful one.
The commit itself it relatively fast but we also update indices there. Therefore, especially for datasets with many partitions >100k or for datasets with many, granular indices, the commit may take a few seconds.

**Comment by brl0** [comment]
Thanks for the responses, very helpful.
