### ISSUE TITLE
Store serializer, dask compute parameters (`num_buckets`, `repartition_ratio`, `shuffle`) into dataset metadata

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#355]

**Comment by fjetter** [comment]
@lr4d can you please provide a description for issues? It is not clear to me what the benefits would be. In particular things like repartition_ratio and shuffle strongly depend on the source of the data and not on the target dataset. Same goes for num_buckets imo

**Comment by fjetter** [comment]
Note that the application can always store these parameters as part of the user metadata and reconstruct and use these as the application sees fit. 

Since the suggested parameters are all non-constant for a given dataset and depend strongly on the application, I don't see the value we could add by extending the metadata format for this. I'll close this issue for, now. If there is more information available, feel free to reopen
