### ISSUE TITLE
Removal of complex input types

### ISSUE THREAD

**Issue by fjetter** [JDASoftwareGroup/kartothek#427]
For mostly historic reasons, kartothek allows input in the form of 

```python
input_data = [
    [
        {
            "data": Dict[str, pandas.DataFrame],
            "secondary_indices": Optional[Dict[str, List[str]]],
            "label": Optional[str]
        },
    ]
] 
```

which allows users a range of features we mostly would like to get rid off
* Multi table writes (deprecated feature in general)
* user calcualted secondary indices (replaced with `secondary_indices` kwarg)
* Explicit labeling of output partitions (should be rather done with partition indices, if needed)

Removal of this in `parse_input_to_metapartition` will allow for significant simplifications in the code base.

There are a few non-trivial consequences by this. In particular this will render pipelines like `merge_datasets_as_delayed` useless since there is no explicit handle for the labels anymore. I firmly believe we should abandon this approach and replace it with a proper join implementation based on indices, which should be a few orders faster anyhow.

@mlondschien you have been involved with these kind of things and I'd like to get some input here. In particular, if we keep the align_dataset and merge pipelines, I would like to know what and how it is actually used for. All workflows I can think of in this area would strongly benefit from proper indexing and/or plain dask usage.

**Comment by mlondschien** [comment]
Hi @fjetter, thanks again for pinging.

We do not currently (or plan to) use multi-table writes or secondary indices. We don't label our output partitions (I understand this is where the parquet files are not named via some hash?).

We had been playing with `merge_datasets_as_delayed` (or rather [`merge_many_datasets_as_delayed`](https://github.com/JDASoftwareGroup/kartothek/pull/243)) in an attempt to divide some of our caching / storage column-wise. This would enable us to more selectively recompute only datasets with affected columns. However, the approach as in the PR turned out to be slow and unsafe. Slow because `pd.concat` is inefficient, unsafe because indices matter and might not match up if we're not careful.

We are currently considering trying out a similar approach (we've learned some lessons), but have not looked into this in much detail. I am certain that we would not use the code in `merge(_many)_datasets_as_delayed` for this (since slow and unsafe). IIUC a better variant  is implemented as part of the `Cube` functionality? We have not looked into this yet.

I am not sure what you refer to with _proper indexing_ in

> All workflows I can think of in this area would strongly benefit from proper indexing and/or plain dask usage.

**Comment by fjetter** [comment]
> I am not sure what you refer to with proper indexing in

With proper indexing I mean using actual kartothek indices. The file labeling thing started off at the beginning of kartothek because we we're lacking some better way of addressing our files. I strongly believe that all functionality this labeling was used for can be replaced by, e.g. partition indices.


> IIUC a better variant is implemented as part of the Cube functionality? We have not looked into this yet.

yes. Cubes offer you to effectively define additional columns in dedicated datasets and the cube interface then joins this properly for you without you noticing. You should definitely check this out if you have workflows like this. It comes with a lot of assumptions about how the data and the datasets should look like. Assumptions we, ourselves, are limited by and are rethinking it but this is always a slow progress. If you encounter some usability issues with this, I'd be happy to hear about it. Mind that this comes with a few performance penalties as well since effectively we are joining/concating pandas dataframes as well

**Comment by mlondschien** [comment]
Is [this](https://github.com/JDASoftwareGroup/kartothek/pull/243/files#diff-2f3d79b8a7bd2cb35cc4d0470bf57d9e6935d2b001e71dbea9bde59e3b0b9ec2R194) what you are referring to as "actual kartothek indices"? I feel like there's some hidden kartothek functionality we've been missing the entire time.

I'll have a look at / experiment with cubes.

**Comment by fjetter** [comment]
> Is this what you are referring to as "actual kartothek indices"? I feel like there's some hidden kartothek functionality we've been missing the entire time.

I'm talking about the keyword arguments `partition_on` and `secondary_indices` and not the filename labels. You can currently use these indices either for predicate based partition pruning or by using the dispatch_by functionality, you should already be aware of. There is no hidden feature I am referring to, I am just pointing out that one _could_ implement a reasonable join with the indices but this hasn't been done, yet
